# specify which database and adapter to use for which environment

development:
  adapter: postgresql
  database: to-do-app-development

test:
  adapter: postgresql
  database: to-do-app-test

production:
  adapter: postgresql
  database: to-do-app-production
